name: Generate Snake Animation

on:
  workflow_dispatch: # handmatig triggeren
  schedule:           # automatisch elke 12 uur
    - cron: "0 */12 * * *"

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          palette: github-dark

      - name: Move snake.svg to assets folder
        run: |
          mkdir -p assets
          mv snake.svg assets/snake.svg

      - name: Commit and push snake.svg
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/snake.svg
          git commit -m "Update snake.svg"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
